services:

  app_planer:
    build:
      context: .
    env_file:
      - .prod.env
    container_name: app_planer
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - ${API_PORT_PROD}:8000

  app_planner_test:
    build:
      context: .
    env_file:
      - .test.env
    container_name: app_planner_test
    command: [ "/fastapi_app/docker/app_test.sh" ]
    ports:
      - ${API_PORT_TEST}:8001